### ISSUE TITLE
中文模式使用右邊數字鍵盤無法直接輸入數字

### ISSUE THREAD

**Issue by paoyuan** [openvanilla/McBopomofoWeb#142]
目前使用 pime 方案，在中文模式下無法直接使用右邊數字鍵盤輸入數字
不知道是否為 web 限制無法識別

**Comment by zonble** [comment]
我覺得比較會是我的問題，我平常大概都是用筆電還有 80% 鍵盤。週末我找個鍵盤來看一下現在的狀況。

**Comment by paoyuan** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#numpad_keys
看起來數字鍵盤真的有額外的定義沒錯

**Comment by paoyuan** [comment]
抱歉，數字鍵可以用了，但不知道可否把數字鍵盤對應的「/」、「-」、「 .」一併加入，因為中文模式下這三個鍵仍然會輸入注音，謝謝

**Comment by zonble** [comment]
請試試看 1.5.4 版。

**Comment by paoyuan** [comment]
1.5.4版本已可以使用，謝謝
