### ISSUE TITLE
PIME 版本中英文混打問題

### ISSUE THREAD

**Issue by paoyuan** [openvanilla/McBopomofoWeb#143]
範例如下圖，「中英文測試」已為確認的部分，理論上應該要送出？
![image](https://github.com/user-attachments/assets/8b980d62-80b0-4727-8623-6db4ab3c4fc9)
但按下Enter後，輸出文字卻變成「test中英文測試」
這問題目前沒辦法找出在何種情境下一定會產生(通訊軟體 Telegram / Teams常發生)，但發生之後就會非常困擾

**Comment by zonble** [comment]
確認一下，這一段事先打「中英文測試」不送出，然後按下 Shift 不放然後按下 test 嗎？我正在想辦法重現。

**Comment by paoyuan** [comment]
先打出「中英文測試」，按下Shift後放掉，再打test

**Comment by zonble** [comment]
請試試看 1.5.4。

**Comment by paoyuan** [comment]
1.5.4版本測試test
UI顯示有點奇怪，中文部分仍然會有底線(如下圖)，回中文位置也無法重新選字
![image](https://github.com/user-attachments/assets/0823b247-79c2-4c43-bcdb-132c8565019f)
要用滑鼠點選輸入框底線才會消失

**Comment by paoyuan** [comment]
剛在 notepad++ 輸入「中文測試...」會有下列不同行為
- 使用數字鍵盤的 . --> 正常
![image](https://github.com/user-attachments/assets/e0012bba-9537-4319-be4b-02b11685fe2e)
- 使用主鍵盤的 . --> 有誤，輸入「中文測試」後，點選Shift放掉，再輸入 ...
顯示異常 (UI沒有顯示最後的 ...)
![image](https://github.com/user-attachments/assets/31952b9b-f26a-493f-ab4b-3ef0e325a967)
結果也異常 (...跑到最前面去了)
![image](https://github.com/user-attachments/assets/8bffbf92-cc6c-446a-8d5b-14645475f961)

**Comment by zonble** [comment]
請試試看 1.5.5。

**Comment by paoyuan** [comment]
1.5.5 版本測試正常，謝謝
