### ISSUE TITLE
PIME 版本，中文選字游標位子問題

### ISSUE THREAD

**Issue by paoyuan** [openvanilla/McBopomofoWeb#155]
想請問，中文模式下，若已選字後，是否可以根據選字字數，自動將游標位子往後移幾個字
其他輸入法有實作這段邏輯，比較方便，謝謝

**Comment by zonble** [comment]
有這項功能，請在設定中選擇「選字之後自動移動游標位置」，然後這個設定只有在選擇是後選字模式時有效。

![image](https://github.com/user-attachments/assets/d2fab49a-7717-44b4-bad2-8fa06e8e81c5)

**Comment by paoyuan** [comment]
好的，謝謝
