### ISSUE TITLE
PIME 版本，中英文模式輸入問題

### ISSUE THREAD

**Issue by paoyuan** [openvanilla/McBopomofoWeb#158]
先輸入中文字後，長按 Shift 後 (原本是要按 Shift + 英文字，但變成 Shift 長按)
此時原本已輸入的中文字會被清空

**Comment by zonble** [comment]
Tab 按鍵的問題是 code 裡頭有個地方打錯，先解決這個。

**Comment by zonble** [comment]
請試試看 1.5.6 版。

**Comment by paoyuan** [comment]
測試OK，謝謝
