### ISSUE TITLE
PIME 版本，快捷鍵輸入問題

### ISSUE THREAD

**Issue by paoyuan** [openvanilla/McBopomofoWeb#159]
- Intellij 有個快捷鍵是 double shift，無法使用 PIME 版本輸入 double shift，只會變成切換中英文模式
- 另外在中文模式下，無法直接輸入 Tab，要切換為英文模式才可以

**Comment by zonble** [comment]
Tab 按鍵的問題是 code 裡頭有個地方打錯，先解決這個。

**Comment by zonble** [comment]
請試試看 1.5.6 版。

**Comment by paoyuan** [comment]
Tab 鍵測試OK，謝謝
